# Chapter45
## 📌문제1

### true or false를 판단하세요.

```
(1) 비동기 함수 내부의 비동기로 동작하는 코드는 비동기 함수가 종료된 이후에 완료된다.
(2) settled 상태에서 비동기 처리가 수행 성공되면 resolve 함수를 호출하여 프로미스를 fulfilled 상태로 변경한다.
(3) 에러 처리는 catch 메서드보다 then 메서드의 두 번째 콜백 함수를 사용하는 것이 더 권장된다.
```

### 답안 작성
```
(1) true
(2) false
(3) false
```
```
(1) (843p) 
비동기 함수란 함수 내부에 비동기로 동작하는 코드를 포함한 함수를 말합니다.
비동기 함수를 호출하면 함수 내부의 비동기로 동작하는 코드가 완료되지 않았다 해도 기다리지 않고 즉시 종료됩니다.

(2) (851p)
settled 상태는 fulfilled, rejected 상태와 상관없이 pending이 아닌 상태로, 비동기 처리가 수행된 상태를 말합니다.
settled 상태가 되면 더는 다른 상태로 변화할 수 없습니다.

(3) (856p)
then 메서드의 두 번째 콜백 함수는 첫 번째 콜백 함수에서 발생한 에러를 캐치하지 못하고
코드가 복잡해져서 가독성이 좋지 않습니다.
또한 then 메서드에 두 번째 콜백 함수를 전달하는 것보다 catch 메서드를 사용하는 것이 가독성이 더 좋고, 명확합니다.
따라서 에러 처리는 then 메서드에서 하지 않고, catch 메서드에서 하는 것을 권장합니다.
```

<br>

## 📌문제2

### 다음 코드 중, catch 코드 블록에서 에러 캐치가 되지 않는 설명하세요.
```js
try {
  setTimeout(() => {
    throw new Error("Error!");
  }, 100);
} catch (e) {
    // 에러 캐치X
  console.error("캐치한 에러", e);
}
```

### 답안 작성
```
(849p)
에러는 호출자 방향(콜스택의 아래방향)으로 전파됩니다.
즉 실행 중인 실행 컨텍스트가 푸시되기 직전에 푸시된 실행 컨텍스트 방향으로 전파됩니다.
하지만 setTimeout 함수의 콜백 함수를 호출한 것은 setTimeout 함수가 아닙니다.
따라서 setTimeout 함수의 콜백 함수가 발생시킨 에러는 catch 블록에서 캐치되지 않습니다.
```

<br>

## 📌문제3
### 다음 코드의 출력 순서를 작성하세요.
```js
setTimeout(() => console.log(1), 0); // (1)

Promise.resolve()
  .then(() => console.log(2)) // (2)
  .then(() => console.log(3)); // (3)
```

### 답안 작성
```
2 -> 3-> 1
```
```
(864p)
프로미스의 후속 처리 메서드는 비동기로 동작하므로 1,2,3 순서로 출력될 것 같은 예상과 달리 2,3,1의 순서로 출력됩니다.
프로미스의 후속 처리 메서드의 콜백 함수는 태스크 큐가 아니라, 마이크태스크 큐에 저장되기 때문입니다.
그 외의 비동기 함수의 콜백 함수나 이벤트 핸들러는 태스크 큐에 일시 정지됩니다.
마이크로태스크 큐는 태스크 큐보다 우선순위가 높기 때문에 2,3,1의 순서로 출력됩니다.
```

<br>

### 다음 실행 결과를 서술하고, 결과의 이유를 이야기해주세요.
```js
try {
	setTimeout(() => {throw new Error('error');}, 0);
} catch (e) {
	console.error('에러 캐치', e);
}
```
### 정답 및 해설
```
아무 일도 일어나지 않는다.
setTimeout이 실행된 이후 즉시 종료되고  try catch
setTimeout 함수의 콜백 함수가 실행될 때 setTimeout 함수는 이미 콜 스택에서 제거된 상태이기
때문에 setTimeout에서 호출된 것이 아니다. 에러는 호출자 방향으로 전파되기 때문에 콜 스택의 
아래 방향으로 전파되지만 이미 실행컨텍스트에는 콜백함수밖에 남지 않았기 때문에 
에러를 탐지하지 못한다. 
```

<br>

## 📌문제8
### true or false를 고르시오
```
(1) then 메서드는 두 개의 콜백 함수를 인수로 전달받고, 만약 콜백 함수에서 프로미스가 아닌 값을 반환하면 암묵적으로 프로미스 객체를 생성해서 반환한다. 
(2)프로미스는 콜백 함수와 달리 콜백 패턴을 사용하지 않기 때문에 콜백 헬이 일어나지 않는다.
(3) Promise.all은 Promise.race와 달리 메서드에 전달된 프로미스 중 하나 이상이
 reject 상태가 되더라도 모두 실행이 끝나야지 프로미스를 반환한다. 
```
### 정답 및 해설
```
(1) true
프로미스는 언제나 프로미스 객체를 반환한다. 
(2) false
프로미스 체이닝을 이용하기 때문에 콜백 헬이 일어나지 않지만 콜백 패턴을 사용한다.
콜백 패턴은 가독성이 좋지 않기 때문에 async/await를 사용해서 해결 가능하다.
(3) false
Promise.race와 Promise.all 둘 다 전달된 프로미스 중 하나라도 rejected상태가 되면 에러를 reject 하는
새로운 프로미스를 즉시 반환한다. 
```

<br>

## 📌문제9
### 다음 예제의 출력 결과를 작성하시오
```js
setTimeout(() => console.log(1), 0);
Promise.resolve()
.then(() => setTimeout(() => console.log(2), 0))
.then(() => console.log(3));
```
### 정답 및 해설
```
3
1
2
프로미스의 후속 처리 메서드의 콜백 함수는 테스크 큐가 아니라 마이크로 테스크 큐에 저장되기 때문에
이벤트 루프에서 먼저 빠져나온다. 콜백 함수 console.log(2)가 테스크 큐에 집어넣어지고, 
3이 출력된다. 그 다음 먼저 테스크 큐에 있던 console.log(1)이 실행되고 console.log(2)가
마지막으로 실행된다. 
```

<br>
